CONFIG_SPI=y

CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610_ALT=y

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
